language: python
python:
  - "2.7"

install:
  - pip install --no-deps -r requirements/dev.txt --use-mirrors
  - cp apk_signer/settings/local.py{-dist,}

script: ./manage.py test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
