language: python
python:
  - "2.7"

install:
  - ./build env dev
  - cp apk_signer/settings/local.py{-dist,}

script: ./venv/bin/python ./manage.py test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always
